name: liquid
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  liquid_flutter: ^18.0.0-0
  liquid_flutter_emd_theme: ^0.0.1-0
  bitsdojo_window: ^0.1.2
  flutter_markdown: ^0.6.12
  flutter_animate: ^4.1.1
  flutter_portal: ^1.1.3
  responsive_builder: ^0.7.0
  syntax_highlight: ^0.2.0
  implicitly_animated_list: ^2.2.0

  provider: ^6.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  go_router:
    git:
      url: https://github.com/ElectricCookie/flutter_packages.git
      path: packages/go_router
  package_info_plus: ^8.0.2
  web: ^1.1.0
  flutter_sticky_header: ^0.7.0
  wolt_modal_sheet: ^0.9.4
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  fuzzy: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  icons_launcher: ^2.1.6
  flutter_oss_licenses: ^2.0.1
  flutter_lints: ^1.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - liquid_flutter_icon.jpg
    - assets/
    - lib/components/

  fonts:
    - family: Lato
      fonts:
        - asset: packages/liquid_flutter/fonts/Lato-Regular.ttf
          weight: 500
        - asset: packages/liquid_flutter/fonts/Lato-Bold.ttf
          weight: 800
    - family: EMD
      fonts:
        - asset: packages/liquid_flutter_emd_theme/fonts/EMD.ttf
    - family: LiquidIcons
      fonts:
        - asset: packages/liquid_flutter_emd_theme/fonts/LiquidIcons.ttf

    - family: NotoSansMono
      fonts:
        - asset: fonts/NotoSansMono-Regular.ttf
          weight: 500
        - asset: fonts/NotoSansMono-Bold.ttf
          weight: 800

icons_launcher:
  image_path: "liquid_flutter_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true

dependency_overrides:
  liquid_flutter:
    path: ./../
