version: 2
updates:
  - package-ecosystem: "pub"
    directories:
      - "/"
      - "/example"
      - "/generators"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"