arb-dir: lib/src/l10n
template-arb-file: app_en.arb
output-localization-file: liquid_localizations.dart
output-class: LiquidLocalizations
preferred-supported-locales: [en]
nullable-getter: false
format: false
use-escaping: true
output-dir: lib/src/l10n/generated
synthetic-package: false
untranslated-messages-file: lib/src/l10n/generated/needTranslation.txt