name: liquid_flutter
description: Liquid Oxygen Components for Flutter
version: 21.0.9-dev.1
repository: https://github.com/emdgroup-liquid/liquid-flutter
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.2
  flutter_animate: ^4.1.1
  haptic_feedback: ">=0.4.2 <0.6.0"
  responsive_builder: ^0.7.0
  multi_split_view: ^3.6.0
  flutter_portal: ^1.1.3
  sensors_plus: ">=5.0.1 <7.0.0"
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  flutter_sticky_header: ^0.7.0
  jiffy: ^6.3.1
  wolt_modal_sheet: ">=0.9.4 <0.12.0"
  fuzzy: ^0.5.1
  device_info_plus: ^11.2.0
  go_router: ^14.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  analyzer: ^6.4.1
  build_runner: ^2.1.10
  flutter_oss_licenses: ">=2.0.1 <4.0.0"
  liquid_generators:
    path: ./generators
  golden_toolkit: ^0.15.0
  change_case: ^2.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Lato
      fonts:
        - asset: lib/fonts/Lato-Regular.ttf
