name: liquid_flutter_monorepo
publish_to: none
environment:
  sdk: ">=3.5.0 <4.0.0"
workspace:
  - packages/liquid_flutter
  - packages/liquid_flutter_emd_theme
  - packages/liquid_flutter_window_utils
  - packages/liquid_flutter/generators
  - packages/liquid_flutter_test_utils
  - packages/liquid_flutter/extension/devtools/liquid_flutter_extension
  - apps/example
dev_dependencies:
  melos: ^7.1.0
