// Autogenerated from Pigeon (v13.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WindowUtilsApi {
  func setWindowSize(width: Int64, height: Int64) throws -> Bool
  func setWindowTitle(title: String) throws
  func setWindowPosition(x: Int64, y: Int64) throws -> Bool
  func startDragging() throws
  func configureWindow() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WindowUtilsApiSetup {
  /// The codec used by WindowUtilsApi.
  /// Sets up an instance of `WindowUtilsApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WindowUtilsApi?) {
    let setWindowSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.setWindowSize", binaryMessenger: binaryMessenger)
    if let api = api {
      setWindowSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let heightArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        do {
          let result = try api.setWindowSize(width: widthArg, height: heightArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setWindowSizeChannel.setMessageHandler(nil)
    }
    let setWindowTitleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.setWindowTitle", binaryMessenger: binaryMessenger)
    if let api = api {
      setWindowTitleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        do {
          try api.setWindowTitle(title: titleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setWindowTitleChannel.setMessageHandler(nil)
    }
    let setWindowPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.setWindowPosition", binaryMessenger: binaryMessenger)
    if let api = api {
      setWindowPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let xArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        let yArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        do {
          let result = try api.setWindowPosition(x: xArg, y: yArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setWindowPositionChannel.setMessageHandler(nil)
    }
    let startDraggingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.startDragging", binaryMessenger: binaryMessenger)
    if let api = api {
      startDraggingChannel.setMessageHandler { _, reply in
        do {
          try api.startDragging()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDraggingChannel.setMessageHandler(nil)
    }
    let configureWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.configureWindow", binaryMessenger: binaryMessenger)
    if let api = api {
      configureWindowChannel.setMessageHandler { _, reply in
        do {
          try api.configureWindow()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureWindowChannel.setMessageHandler(nil)
    }
  }
}
