import 'package:flutter/material.dart';
import 'package:liquid_flutter/liquid_flutter.dart';

LdButton _LdButton_ghost({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return LdButton(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: LdButtonMode.ghost,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

LdButton _LdButton_vague({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return LdButton(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: LdButtonMode.vague,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

LdButton _LdButton_outline({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return LdButton(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: LdButtonMode.outline,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

LdButton _LdButton_filled({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return LdButton(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: LdButtonMode.filled,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

Widget Function() _LdButton_warning({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return () => Builder(
        builder: (BuildContext context) => LdButton(
          child: child,
          onPressed: onPressed,
          autoLoading: autoLoading,
          borderRadius: borderRadius,
          color: LdTheme.of(context).warning,
          active: active,
          width: width,
          disabled: disabled,
          focusNode: focusNode,
          autoFocus: autoFocus,
          alignment: alignment,
          leading: leading,
          circular: circular,
          loading: loading,
          loadingText: loadingText,
          errorText: errorText,
          mode: mode,
          progress: progress,
          size: size,
          trailing: trailing,
          key: key,
        ),
      );
}

Widget Function() _LdButton_error({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return () => Builder(
        builder: (BuildContext context) => LdButton(
          child: child,
          onPressed: onPressed,
          autoLoading: autoLoading,
          borderRadius: borderRadius,
          color: LdTheme.of(context).error,
          active: active,
          width: width,
          disabled: disabled,
          focusNode: focusNode,
          autoFocus: autoFocus,
          alignment: alignment,
          leading: leading,
          circular: circular,
          loading: loading,
          loadingText: loadingText,
          errorText: errorText,
          mode: mode,
          progress: progress,
          size: size,
          trailing: trailing,
          key: key,
        ),
      );
}

Widget Function() _LdButton_success({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return () => Builder(
        builder: (BuildContext context) => LdButton(
          child: child,
          onPressed: onPressed,
          autoLoading: autoLoading,
          borderRadius: borderRadius,
          color: LdTheme.of(context).success,
          active: active,
          width: width,
          disabled: disabled,
          focusNode: focusNode,
          autoFocus: autoFocus,
          alignment: alignment,
          leading: leading,
          circular: circular,
          loading: loading,
          loadingText: loadingText,
          errorText: errorText,
          mode: mode,
          progress: progress,
          size: size,
          trailing: trailing,
          key: key,
        ),
      );
}

LdButton LdButton_ghost({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return _LdButton_ghost(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: mode,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

LdButton LdButton_vague({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return _LdButton_vague(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: mode,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

LdButton LdButton_outline({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return _LdButton_outline(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: mode,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

LdButton LdButton_filled({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return _LdButton_filled(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: mode,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

Widget Function() LdButton_warning({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return _LdButton_warning(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: mode,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

Widget Function() LdButton_error({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return _LdButton_error(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: mode,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}

Widget Function() LdButton_success({
  required Widget child,
  required Function onPressed,
  bool autoLoading = true,
  BorderRadius? borderRadius,
  LdColor? color,
  bool? active,
  double? width,
  bool disabled = false,
  FocusNode? focusNode,
  bool autoFocus = false,
  MainAxisAlignment? alignment,
  Widget? leading,
  bool? circular,
  bool loading = false,
  String? loadingText,
  String? errorText,
  LdButtonMode mode = LdButtonMode.filled,
  double? progress,
  LdSize size = LdSize.m,
  Widget? trailing,
  Key? key,
}) {
  return _LdButton_success(
    child: child,
    onPressed: onPressed,
    autoLoading: autoLoading,
    borderRadius: borderRadius,
    color: color,
    active: active,
    width: width,
    disabled: disabled,
    focusNode: focusNode,
    autoFocus: autoFocus,
    alignment: alignment,
    leading: leading,
    circular: circular,
    loading: loading,
    loadingText: loadingText,
    errorText: errorText,
    mode: mode,
    progress: progress,
    size: size,
    trailing: trailing,
    key: key,
  );
}
