include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    - example/lib/**/*.demo.dart
    - lib/oss_licenses.dart
    - example/build/**
    - lib/src/*.variants.g.dart
    - lib/src/**/*.variants.g.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  page_width: 120
