// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct WindowState: Hashable {
  var x: Int64
  var y: Int64
  var width: Int64
  var height: Int64
  var isMaximized: Bool
  var isMinimized: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WindowState? {
    let x = pigeonVar_list[0] as! Int64
    let y = pigeonVar_list[1] as! Int64
    let width = pigeonVar_list[2] as! Int64
    let height = pigeonVar_list[3] as! Int64
    let isMaximized = pigeonVar_list[4] as! Bool
    let isMinimized = pigeonVar_list[5] as! Bool

    return WindowState(
      x: x,
      y: y,
      width: width,
      height: height,
      isMaximized: isMaximized,
      isMinimized: isMinimized
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
      isMaximized,
      isMinimized,
    ]
  }
  static func == (lhs: WindowState, rhs: WindowState) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Rect: Hashable {
  var left: Int64
  var top: Int64
  var right: Int64
  var bottom: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Rect? {
    let left = pigeonVar_list[0] as! Int64
    let top = pigeonVar_list[1] as! Int64
    let right = pigeonVar_list[2] as! Int64
    let bottom = pigeonVar_list[3] as! Int64

    return Rect(
      left: left,
      top: top,
      right: right,
      bottom: bottom
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      right,
      bottom,
    ]
  }
  static func == (lhs: Rect, rhs: Rect) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return WindowState.fromList(self.readValue() as! [Any?])
    case 130:
      return Rect.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WindowState {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Rect {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WindowUtilsApi {
  func setWindowSize(width: Int64, height: Int64) throws -> Bool
  func setWindowTitle(title: String) throws
  func setWindowPosition(x: Int64, y: Int64) throws -> Bool
  func startDragging() throws
  func configureWindow() throws
  func closeWindow() throws
  func minimizeWindow() throws
  func maximizeWindow() throws
  func isWindowMaximized() throws -> Bool
  func getWindowState() throws -> WindowState
  func getScreenRadius() throws -> Double
  func getScreenCornerRadiiDebugLog() throws -> String
  func setSystemGestureExclusionRects(rects: [Rect]) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WindowUtilsApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WindowUtilsApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WindowUtilsApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setWindowSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.setWindowSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWindowSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let widthArg = args[0] as! Int64
        let heightArg = args[1] as! Int64
        do {
          let result = try api.setWindowSize(width: widthArg, height: heightArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setWindowSizeChannel.setMessageHandler(nil)
    }
    let setWindowTitleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.setWindowTitle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWindowTitleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        do {
          try api.setWindowTitle(title: titleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setWindowTitleChannel.setMessageHandler(nil)
    }
    let setWindowPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.setWindowPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWindowPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let xArg = args[0] as! Int64
        let yArg = args[1] as! Int64
        do {
          let result = try api.setWindowPosition(x: xArg, y: yArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setWindowPositionChannel.setMessageHandler(nil)
    }
    let startDraggingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.startDragging\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDraggingChannel.setMessageHandler { _, reply in
        do {
          try api.startDragging()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDraggingChannel.setMessageHandler(nil)
    }
    let configureWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.configureWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureWindowChannel.setMessageHandler { _, reply in
        do {
          try api.configureWindow()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureWindowChannel.setMessageHandler(nil)
    }
    let closeWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.closeWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeWindowChannel.setMessageHandler { _, reply in
        do {
          try api.closeWindow()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeWindowChannel.setMessageHandler(nil)
    }
    let minimizeWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.minimizeWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      minimizeWindowChannel.setMessageHandler { _, reply in
        do {
          try api.minimizeWindow()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      minimizeWindowChannel.setMessageHandler(nil)
    }
    let maximizeWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.maximizeWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      maximizeWindowChannel.setMessageHandler { _, reply in
        do {
          try api.maximizeWindow()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      maximizeWindowChannel.setMessageHandler(nil)
    }
    let isWindowMaximizedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.isWindowMaximized\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWindowMaximizedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWindowMaximized()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWindowMaximizedChannel.setMessageHandler(nil)
    }
    let getWindowStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.getWindowState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWindowStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getWindowState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getWindowStateChannel.setMessageHandler(nil)
    }
    let getScreenRadiusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.getScreenRadius\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getScreenRadiusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getScreenRadius()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getScreenRadiusChannel.setMessageHandler(nil)
    }
    let getScreenCornerRadiiDebugLogChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.getScreenCornerRadiiDebugLog\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getScreenCornerRadiiDebugLogChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getScreenCornerRadiiDebugLog()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getScreenCornerRadiiDebugLogChannel.setMessageHandler(nil)
    }
    let setSystemGestureExclusionRectsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.liquid_flutter_window_utils.WindowUtilsApi.setSystemGestureExclusionRects\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSystemGestureExclusionRectsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let rectsArg = args[0] as! [Rect]
        do {
          try api.setSystemGestureExclusionRects(rects: rectsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSystemGestureExclusionRectsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WindowStateEventApiProtocol {
  func onWindowStateChanged(state stateArg: WindowState, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWindowReady(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WindowStateEventApi: WindowStateEventApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onWindowStateChanged(state stateArg: WindowState, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_flutter_window_utils.WindowStateEventApi.onWindowStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onWindowReady(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.liquid_flutter_window_utils.WindowStateEventApi.onWindowReady\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
