name: liquid_flutter_md
description: "Markdown rendering package for Liquid Flutter"
version: 0.0.1

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  liquid_flutter: any
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


