import 'package:liquid/demos/task_demo/task.dart';

var testData = [
  Task(1, "Build spaceship 🚀 ", DateTime.now().add(const Duration(days: 30)),
      false, DateTime.now()),
  Task(2, "Build cool Flutter app",
      DateTime.now().add(const Duration(days: 30)), false, DateTime.now()),
  Task(3, "Prepare for team meeting",
      DateTime.now().add(const Duration(days: 1)), false, DateTime.now()),
  Task(4, "Buy groceries", DateTime.now(), true, DateTime.now()),
  Task(5, "Learn quantum computing",
      DateTime.now().add(const Duration(days: 365)), false, DateTime.now()),
  Task(6, "Fix critical bug in production",
      DateTime.now().subtract(const Duration(days: 1)), false, DateTime.now()),
  Task(7, "Schedule dentist appointment",
      DateTime.now().add(const Duration(days: 7)), false, DateTime.now()),
  Task(8, "Write documentation", DateTime.now().add(const Duration(days: 3)),
      true, DateTime.now()),
  Task(9, "Review pull requests", DateTime.now(), false, DateTime.now()),
  Task(10, "Update dependencies", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
  Task(
      11,
      "Plan team offsite",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(12, "Backup database", DateTime.now(), true, DateTime.now()),
  Task(13, "Read a new Flutter article",
      DateTime.now().add(const Duration(days: 3)), false, DateTime.now()),
  Task(
      14,
      "Refactor old codebase",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(15, "Organize workspace", DateTime.now(), false, DateTime.now()),
  Task(16, "Update project roadmap",
      DateTime.now().add(const Duration(days: 1)), false, DateTime.now()),
  Task(17, "Test new features", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
  Task(18, "Clean up email inbox", DateTime.now(), false, DateTime.now()),
  Task(
      19,
      "Prepare sprint demo",
      DateTime.now().add(Duration(days: (5 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(20, "Sync with design team", DateTime.now().add(const Duration(days: 7)),
      false, DateTime.now()),
  Task(
      21,
      "Walk the dog",
      DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day,
          23, 59),
      false,
      DateTime.now()),
  Task(
      22,
      "Call mom",
      DateTime.now().add(Duration(days: (7 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(
      23,
      "Finish reading book",
      DateTime(
          DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false,
      DateTime.now()),
  Task(24, "Practice piano", DateTime.now().add(const Duration(days: 1)), false,
      DateTime.now()),
  Task(25, "Water the plants", DateTime.now(), false, DateTime.now()),
  Task(26, "Update LinkedIn profile",
      DateTime.now().add(const Duration(days: 3)), false, DateTime.now()),
  Task(
      27,
      "Book flight tickets",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(28, "Renew gym membership", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
  Task(
      29,
      "Submit expense report",
      DateTime.now().add(Duration(days: (5 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(
      30,
      "Brainstorm blog ideas",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(
      31,
      "Organize digital photos",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(32, "Update resume", DateTime.now().add(const Duration(days: 7)), false,
      DateTime.now()),
  Task(
      33,
      "Research new technologies",
      DateTime(
          DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false,
      DateTime.now()),
  Task(
      34,
      "Plan birthday party",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(35, "Fix broken chair", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
  Task(36, "Learn Spanish basics",
      DateTime.now().add(const Duration(days: 365)), false, DateTime.now()),
  Task(37, "Create workout routine",
      DateTime.now().add(const Duration(days: 1)), false, DateTime.now()),
  Task(38, "Backup important files", DateTime.now(), true, DateTime.now()),
  Task(39, "Schedule car maintenance",
      DateTime.now().add(const Duration(days: 7)), false, DateTime.now()),
  Task(
      40,
      "Write thank you notes",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(41, "Update phone apps", DateTime.now(), false, DateTime.now()),
  Task(
      42,
      "Plan summer vacation",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(43, "Fix leaky faucet", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
  Task(44, "Learn to cook pasta", DateTime.now().add(const Duration(days: 7)),
      false, DateTime.now()),
  Task(
      45,
      "Organize closet",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(
      46,
      "Update insurance policy",
      DateTime(
          DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false,
      DateTime.now()),
  Task(47, "Practice meditation", DateTime.now(), true, DateTime.now()),
  Task(
      48,
      "Fix garden fence",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7 + 7)),
      false,
      DateTime.now()),
  Task(
      49,
      "Learn guitar chords",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(50, "Update emergency contacts",
      DateTime.now().add(const Duration(days: 3)), false, DateTime.now()),
  Task(51, "Plan family dinner", DateTime.now().add(const Duration(days: 7)),
      false, DateTime.now()),
  Task(52, "Fix computer issues",
      DateTime.now().subtract(const Duration(days: 1)), false, DateTime.now()),
  Task(53, "Learn to swim", DateTime.now().add(const Duration(days: 365)),
      false, DateTime.now()),
  Task(
      54,
      "Organize garage",
      DateTime(
          DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false,
      DateTime.now()),
  Task(55, "Update will", DateTime.now().add(const Duration(days: 365)), false,
      DateTime.now()),
  Task(
      56,
      "Fix bicycle tire",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(
      57,
      "Learn calligraphy",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(58, "Update pet vaccinations",
      DateTime.now().add(const Duration(days: 7)), false, DateTime.now()),
  Task(59, "Plan retirement", DateTime.now().add(const Duration(days: 365)),
      false, DateTime.now()),
  Task(60, "Fix kitchen cabinet", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
  Task(
      61,
      "Learn to dance",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(
      62,
      "Organize bookshelf",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(63, "Update passport", DateTime.now().add(const Duration(days: 365)),
      false, DateTime.now()),
  Task(64, "Fix door lock", DateTime.now().subtract(const Duration(days: 1)),
      false, DateTime.now()),
  Task(
      65,
      "Learn to paint",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(66, "Update home security", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
  Task(67, "Plan home renovation",
      DateTime.now().add(const Duration(days: 365)), false, DateTime.now()),
  Task(
      68,
      "Fix window blinds",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(
      69,
      "Learn to sew",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(
      70,
      "Update family photos",
      DateTime(
          DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false,
      DateTime.now()),
  Task(71, "Plan camping trip", DateTime.now().add(const Duration(days: 365)),
      false, DateTime.now()),
  Task(72, "Fix lawn mower", DateTime.now().add(const Duration(days: 3)), false,
      DateTime.now()),
  Task(
      73,
      "Learn to fish",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(
      74,
      "Organize tool shed",
      DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)),
      false,
      DateTime.now()),
  Task(
      75,
      "Update medical records",
      DateTime(
          DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false,
      DateTime.now()),
  Task(76, "Fix porch steps", DateTime.now().subtract(const Duration(days: 1)),
      false, DateTime.now()),
  Task(
      77,
      "Learn to knit",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(
      78,
      "Update car registration",
      DateTime(
          DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false,
      DateTime.now()),
  Task(79, "Plan road trip", DateTime.now().add(const Duration(days: 365)),
      false, DateTime.now()),
  Task(80, "Fix shower head", DateTime.now().add(const Duration(days: 3)),
      false, DateTime.now()),
];
