name: liquid_generators
description: Generators for liquid_flutter
version: 0.0.01
resolution: workspace
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  analyzer: any
  build: ^2.4.1
  code_builder: ^4.8.0
  glob: ^2.0.2
  build_config: ^1.1.1
  source_gen: any
  dart_style: any
  flutter_lints: ^6.0.0
  path: ^1.9.0
  collection: ^1.19.0
  pub_semver: ^2.2.0
