import 'package:liquid/demos/task_demo/task.dart';

var testData = [
  Task(1, "Build spaceship", DateTime.now().add(const Duration(days: 30)), false, DateTime.now(), emoji: "🚀"),
  Task(2, "Build cool Flutter app", DateTime.now().add(const Duration(days: 30)), false, DateTime.now(), emoji: "🦋"),
  Task(3, "Prepare for team meeting", DateTime.now().add(const Duration(days: 1)), false, DateTime.now(), emoji: "👥"),
  Task(4, "Buy groceries", DateTime.now(), true, DateTime.now(), emoji: "🛒"),
  Task(5, "Learn quantum computing", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "⚛️"),
  Task(6, "Fix critical bug in production", DateTime.now().subtract(const Duration(days: 1)), false, DateTime.now(), emoji: "🐛"),
  Task(7, "Schedule dentist appointment", DateTime.now().add(const Duration(days: 7)), false, DateTime.now(), emoji: "🦷"),
  Task(8, "Write documentation", DateTime.now().add(const Duration(days: 3)), true, DateTime.now(), emoji: "📝"),
  Task(9, "Review pull requests", DateTime.now(), false, DateTime.now(), emoji: "👀"),
  Task(10, "Update dependencies", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "📦"),
  Task(11, "Plan team offsite", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🏕️"),
  Task(12, "Backup database", DateTime.now(), true, DateTime.now(), emoji: "💾"),
  Task(13, "Read a new Flutter article", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "📰"),
  Task(14, "Refactor old codebase", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🔧"),
  Task(15, "Organize workspace", DateTime.now(), false, DateTime.now(), emoji: "🗂️"),
  Task(16, "Update project roadmap", DateTime.now().add(const Duration(days: 1)), false, DateTime.now(), emoji: "🗺️"),
  Task(17, "Test new features", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🧪"),
  Task(18, "Clean up email inbox", DateTime.now(), false, DateTime.now(), emoji: "📧"),
  Task(19, "Prepare sprint demo", DateTime.now().add(Duration(days: (5 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "🎤"),
  Task(20, "Sync with design team", DateTime.now().add(const Duration(days: 7)), false, DateTime.now(), emoji: "🎨"),
  Task(21, "Walk the dog", DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day, 23, 59), false,
      DateTime.now(), emoji: "🐕"),
  Task(22, "Call mom", DateTime.now().add(Duration(days: (7 - DateTime.now().weekday) % 7)), false, DateTime.now(), emoji: "📞"),
  Task(23, "Finish reading book", DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 15), false,
      DateTime.now(), emoji: "📚"),
  Task(24, "Practice piano", DateTime.now().add(const Duration(days: 1)), false, DateTime.now(), emoji: "🎹"),
  Task(25, "Water the plants", DateTime.now(), false, DateTime.now(), emoji: "🪴"),
  Task(26, "Update LinkedIn profile", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "💼"),
  Task(27, "Book flight tickets", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "✈️"),
  Task(28, "Renew gym membership", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "💪"),
  Task(29, "Submit expense report", DateTime.now().add(Duration(days: (5 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "💰"),
  Task(30, "Brainstorm blog ideas", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "💡"),
  Task(31, "Organize digital photos", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "📸"),
  Task(32, "Update resume", DateTime.now().add(const Duration(days: 7)), false, DateTime.now(), emoji: "📄"),
  Task(33, "Research new technologies", DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false, DateTime.now(), emoji: "🔬"),
  Task(34, "Plan birthday party", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🎂"),
  Task(35, "Fix broken chair", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🪑"),
  Task(36, "Learn Spanish basics", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "🇪🇸"),
  Task(37, "Create workout routine", DateTime.now().add(const Duration(days: 1)), false, DateTime.now(), emoji: "🏋️"),
  Task(38, "Backup important files", DateTime.now(), true, DateTime.now(), emoji: "💾"),
  Task(39, "Schedule car maintenance", DateTime.now().add(const Duration(days: 7)), false, DateTime.now(), emoji: "🚗"),
  Task(40, "Write thank you notes", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "💌"),
  Task(41, "Update phone apps", DateTime.now(), false, DateTime.now(), emoji: "📱"),
  Task(42, "Plan summer vacation", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🏖️"),
  Task(43, "Fix leaky faucet", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🚿"),
  Task(44, "Learn to cook pasta", DateTime.now().add(const Duration(days: 7)), false, DateTime.now(), emoji: "🍝"),
  Task(45, "Organize closet", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "👔"),
  Task(46, "Update insurance policy", DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false, DateTime.now(), emoji: "📋"),
  Task(47, "Practice meditation", DateTime.now(), true, DateTime.now(), emoji: "🧘"),
  Task(48, "Fix garden fence", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7 + 7)), false,
      DateTime.now(), emoji: "🌳"),
  Task(49, "Learn guitar chords", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🎸"),
  Task(50, "Update emergency contacts", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🆘"),
  Task(51, "Plan family dinner", DateTime.now().add(const Duration(days: 7)), false, DateTime.now(), emoji: "🍽️"),
  Task(52, "Fix computer issues", DateTime.now().subtract(const Duration(days: 1)), false, DateTime.now(), emoji: "💻"),
  Task(53, "Learn to swim", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "🏊"),
  Task(54, "Organize garage", DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 15), false,
      DateTime.now(), emoji: "🏠"),
  Task(55, "Update will", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "📜"),
  Task(56, "Fix bicycle tire", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "🚲"),
  Task(57, "Learn calligraphy", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "✒️"),
  Task(58, "Update pet vaccinations", DateTime.now().add(const Duration(days: 7)), false, DateTime.now(), emoji: "💉"),
  Task(59, "Plan retirement", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "🏡"),
  Task(60, "Fix kitchen cabinet", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🍳"),
  Task(61, "Learn to dance", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "💃"),
  Task(62, "Organize bookshelf", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "📚"),
  Task(63, "Update passport", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "🛂"),
  Task(64, "Fix door lock", DateTime.now().subtract(const Duration(days: 1)), false, DateTime.now(), emoji: "🔒"),
  Task(65, "Learn to paint", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🖌️"),
  Task(66, "Update home security", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🔐"),
  Task(67, "Plan home renovation", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "🏗️"),
  Task(68, "Fix window blinds", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "🪟"),
  Task(69, "Learn to sew", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🧵"),
  Task(70, "Update family photos", DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 15), false,
      DateTime.now(), emoji: "🖼️"),
  Task(71, "Plan camping trip", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "⛺"),
  Task(72, "Fix lawn mower", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🌱"),
  Task(73, "Learn to fish", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🎣"),
  Task(74, "Organize tool shed", DateTime.now().add(Duration(days: (6 - DateTime.now().weekday) % 7)), false,
      DateTime.now(), emoji: "🔨"),
  Task(75, "Update medical records", DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 15),
      false, DateTime.now(), emoji: "🏥"),
  Task(76, "Fix porch steps", DateTime.now().subtract(const Duration(days: 1)), false, DateTime.now(), emoji: "🪜"),
  Task(77, "Learn to knit", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day), false,
      DateTime.now(), emoji: "🧶"),
  Task(78, "Update car registration", DateTime(DateTime.now().year, DateTime.now().month + 1, DateTime.now().day),
      false, DateTime.now(), emoji: "🚙"),
  Task(79, "Plan road trip", DateTime.now().add(const Duration(days: 365)), false, DateTime.now(), emoji: "🛣️"),
  Task(80, "Fix shower head", DateTime.now().add(const Duration(days: 3)), false, DateTime.now(), emoji: "🚿"),
];
